name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -al  # Menampilkan isi direktori untuk memastikan file-file yang diperlukan ada

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install

      - name: Build aplikasi
        run: npm run build

      - name: Deploy to Railway
        run: railway up --environment production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Run tests
        run: npm test
