name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/cli.sh | sh
          export PATH="$PATH:$HOME/.railway/bin"

      - name: Deploy to Railway
        run: railway up --environment production
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}  
