name: CI/CD Pipeline
on: 
  push:
    branches:
      - main
      - feature-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v2

      - name: Menjalankan script
        run: echo "Hello CI/CD"
